<a href="https://colab.research.google.com/github/RichardLDM/AI-enginering/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

arr = np.array([1, 3, 5, 7])
print("numpy array:", arr)

numpy array: [1 3 5 7]


In [6]:
arr2 = np.array([[1, 3, 5, 7], [4, 6, 8, 9]])
print("numpy array2:", arr2)

arr2.shape

numpy array2: [[1 3 5 7]
 [4 6 8 9]]


(2, 4)

In [7]:
# dtype()
a = np.array([1, 2, 3])
print(a.dtype)

b = np.array([1.2, 3.4, 5.6])
print(b.dtype)

int64
float64


In [10]:
# reshape()
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print("shaped array:", b)

shaped array: [[1 2 3]
 [4 5 6]]


In [11]:
# astype()
a = np.array([1, 2, 3])
b = a.astype(float)
print("float:", b)

float: [1. 2. 3.]


In [14]:
# np.zeros(), np.ones() => dummy data
z = np.zeros((2, 3))
o = np.ones((2, 3))

print("zeros:", z)
print("ones:", o)

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# ndim()
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])

print("a ndim:", a.ndim)
print("b ndim:", b.ndim)

a ndim: 1
b ndim: 2


In [18]:
# arange()
a = np.arange(1, 6)
print("arrange:", a)

arrange: [1 2 3 4 5]


In [20]:
# sum(), mean(), max(), min()

a = np.array([1, 2, 3, 4])

print("sum:", a.sum())
print("mean:", a.mean())
print("max:", a.max())
print("min:", a.min())

sum: 10
mean: 2.5
max: 4
min: 1


In [21]:
# flatten()

a = np.array([[1,2], [3, 4]])
print("flatten:", a.flatten())

flatten: [1 2 3 4]


In [22]:
# T (Transpose)

a = np.array([[1, 2], [ 3, 4]])
print("transpose:", a.T)

transpose: [[1 3]
 [2 4]]


In [28]:
# dot() @
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])

print("dot/multiplication:", a.dot(b))

dot/multiplication: [[ 4  4]
 [10  8]]


In [30]:
# random.rand()
a = np.random.rand(2, 3) # => 0.0 and 1.0 / included / 1.0 excluded
print("random rand:", a)

random rand: [[0.61381046 0.96236418 0.72717951]
 [0.18793113 0.60973478 0.94278658]]
